name: gh-pages
on:
  push:
    branches:
      - main

jobs:
  demo:
    name: wasm demo
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo
    steps:
      - uses: actions/checkout@v4
      # Waiting for new wasm-bindgen release to run with newer rust:
      # https://github.com/rustwasm/wasm-bindgen/issues/4211
      - uses: dtolnay/rust-toolchain@1.81

      - run: yarn

      - run: yarn build

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.6.9
        with:
          branch: gh-pages
          folder: demo/dist
          clean: true
